# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
# Software package configuration for esq
# This file defines which packages to track for system information collection

system_packages:
  - docker-ce
  - ffmpeg

python_packages:
  - openvino
  - optimum-intel
  - ultralytics
  - huggingface-hub
  - modelscope
  - kagglehub
  - datasets
  - docker
  - nncf
  - py-libnuma
  - openvino_tokenizers
  - transformers
  - pydub
