# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# Software package configuration for sysagent
# This file defines which packages to track for system information collection

system_packages:
  - intel-driver-compiler-npu
  - intel-fw-npu
  - intel-gsc
  - intel-level-zero-npu
  - intel-media-va-driver-non-free
  - intel-opencl-icd
  - libdrm-intel1
  - libze-intel-gpu1

python_packages:
  - docker
  - openvino
  - pytest
  - allure-pytest
  - psutil
  - requests
  - numpy
  - matplotlib
  - py-cpuinfo
